spring.application.name=MoneyFlow

cors.origins=${CORS_ORIGINS:http://localhost:4200}

spring.profiles.active=${APP_PROFILE:dev}

#Secret word to create Token
api.security.token.secret=${JWT_SECRET}

spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect