spring.application.name=MoneyFlow

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_BASE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Configurações para executar o import.sql
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
# OU especificamente para o Hibernate:
spring.jpa.properties.hibernate.hbm2ddl.import_files=import.sql

# Configura o timezone para UTC, garantindo consistência nas operações de data/hora
spring.jpa.properties.hibernate.jdbc.time_zone=UTC