-- Inserção do usuário
INSERT INTO users (id, name, email, login, password, status, role) VALUES (gen_random_uuid(), 'Administrator', 'admin@email.com', 'admin', '$2a$10$WG9kEmAUsx9cTIBmdEynVOXthtZ/VmFTNubCutii5foQDoRAkq3eS', 'ACTIVE', 'ADMIN');

-- Inserção da carteira e captura do ID
INSERT INTO wallets (id, name, description, active) VALUES (gen_random_uuid(), 'Minha Carteira', 'Carteira física', true)
INSERT INTO wallets (id, name, description, active) VALUES (gen_random_uuid(), 'Nubank', 'Banco Digital', true)


-- Janeiro 2024
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id) VALUES (gen_random_uuid(), 'Salário mensal', 4500.00, '2025-01-05', 'INCOME', 'SALARY', null, 'Pagamento salário Janeiro', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'));

-- Janeiro 2024
-- Minha Carteira (25 transações)
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Salário mensal', 4500.00, '2024-01-05', 'INCOME', 'SALARY', null, 'Pagamento salário Janeiro', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-05');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Aluguel recebido', 1200.00, '2024-01-10', 'INCOME', 'RENTAL', null, 'Apartamento centro', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-12');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Supermercado', 350.75, '2024-01-12', 'EXPENSE', null, 'FOOD', 'Compras mensais', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Juros investimentos', 150.20, '2024-01-15', 'INCOME', 'INTEREST', null, 'Rendimento CDB', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-16');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Academia', 120.00, '2024-01-18', 'EXPENSE', null, 'HEALTH', 'Mensalidade', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-20');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Presente de aniversário', 200.00, '2024-01-20', 'INCOME', 'GIFTS', null, 'Presente da mãe', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-21');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Uber', 45.50, '2024-01-22', 'EXPENSE', null, 'TRANSPORT', 'Viagem aeroporto', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Netflix', 39.90, '2024-01-25', 'EXPENSE', null, 'ENTERTAINMENT', 'Assinatura mensal', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-26');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Venda de equipamentos', 500.00, '2024-01-28', 'INCOME', 'OTHER', null, 'Venda câmera fotográfica', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-29');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Farmácia', 78.30, '2024-01-30', 'EXPENSE', null, 'HEALTH', 'Remédios', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Investimento inicial', 1000.00, '2024-01-02', 'EXPENSE', null, 'OTHER', 'Aporte em ações', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-03');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Restaurante', 85.00, '2024-01-07', 'EXPENSE', null, 'FOOD', 'Jantar com amigos', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-08');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Gasolina', 180.00, '2024-01-09', 'EXPENSE', null, 'TRANSPORT', 'Abastecimento carro', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-10');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Curso online', 250.00, '2024-01-14', 'EXPENSE', null, 'EDUCATION', 'Curso de programação', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Dividendos', 320.50, '2024-01-16', 'INCOME', 'INVESTMENT', null, 'Dividendos ações', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-17');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Manutenção carro', 450.00, '2024-01-19', 'EXPENSE', null, 'TRANSPORT', 'Troca de óleo', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-20');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Presente de casamento', 300.00, '2024-01-21', 'EXPENSE', null, 'OTHER', 'Presente para amigo', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Freelance', 800.00, '2024-01-23', 'INCOME', 'OTHER', null, 'Projeto desenvolvimento', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-25');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Cinema', 60.00, '2024-01-26', 'EXPENSE', null, 'ENTERTAINMENT', 'Ingressos e pipoca', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-27');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Conta de luz', 120.50, '2024-01-29', 'EXPENSE', null, 'HOME', 'Energia elétrica', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Venda de livros', 75.00, '2024-01-03', 'INCOME', 'OTHER', null, 'Livros usados', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-04');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Almoço trabalho', 45.00, '2024-01-06', 'EXPENSE', null, 'FOOD', 'Reunião com cliente', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-07');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Seguro carro', 350.00, '2024-01-08', 'EXPENSE', null, 'TRANSPORT', 'Parcela anual', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-09');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Rendimento poupança', 42.30, '2024-01-11', 'INCOME', 'INTEREST', null, 'Poupança bancária', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-12');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Material escritório', 65.00, '2024-01-13', 'EXPENSE', null, 'HOME', 'Papel e canetas', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Consulta médica', 200.00, '2024-01-17', 'EXPENSE', null, 'HEALTH', 'Clínico geral', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2024-01-18');

-- Nubank (25 transações)
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Salário freelancer', 1800.00, '2024-01-05', 'INCOME', 'SALARY', null, 'Pagamento projeto', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-06');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Dividendos FIIs', 280.50, '2024-01-10', 'INCOME', 'INVESTMENT', null, 'Fundos Imobiliários', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-11');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Ifood', 65.00, '2024-01-12', 'EXPENSE', null, 'FOOD', 'Jantar delivery', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-13');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Spotify', 19.90, '2024-01-15', 'EXPENSE', null, 'ENTERTAINMENT', 'Assinatura mensal', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Transferência recebida', 300.00, '2024-01-18', 'INCOME', 'GIFTS', null, 'Presente amigo', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-19');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Compras online', 120.00, '2024-01-20', 'EXPENSE', null, 'OTHER', 'Amazon', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-21');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Taxi', 35.00, '2024-01-22', 'EXPENSE', null, 'TRANSPORT', 'Volta da festa', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Reembolso', 50.00, '2024-01-25', 'INCOME', 'OTHER', null, 'Reembolso consulta', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-26');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Assinatura jornal', 29.90, '2024-01-28', 'EXPENSE', null, 'EDUCATION', 'Jornal digital', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-29');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Doação', 100.00, '2024-01-30', 'EXPENSE', null, 'OTHER', 'Doação para ONG', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Rendimento CDB', 45.20, '2024-01-02', 'INCOME', 'INTEREST', null, 'CDB Banco', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-03');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Cinema', 70.00, '2024-01-07', 'EXPENSE', null, 'ENTERTAINMENT', 'Ingressos', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-08');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Transferência poupança', 500.00, '2024-01-09', 'EXPENSE', null, 'OTHER', 'Aporte poupança', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-10');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Curso online', 199.90, '2024-01-14', 'EXPENSE', null, 'EDUCATION', 'Curso de inglês', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Venda de roupas', 150.00, '2024-01-16', 'INCOME', 'OTHER', null, 'Roupas usadas', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-17');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Farmácia', 55.00, '2024-01-19', 'EXPENSE', null, 'HEALTH', 'Remédios', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-20');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Presente', 80.00, '2024-01-21', 'EXPENSE', null, 'OTHER', 'Presente amigo', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Freelance design', 350.00, '2024-01-23', 'INCOME', 'OTHER', null, 'Projeto logo', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-24');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Livros digitais', 45.00, '2024-01-26', 'EXPENSE', null, 'EDUCATION', 'E-books', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-27');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Assinatura VPN', 12.90, '2024-01-29', 'EXPENSE', null, 'OTHER', 'Serviço VPN', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Cashback', 15.00, '2024-01-03', 'INCOME', 'OTHER', null, 'Cashback compras', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-04');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Cafeteria', 25.00, '2024-01-06', 'EXPENSE', null, 'FOOD', 'Café com amigos', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-07');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Transferência entre contas', 200.00, '2024-01-08', 'EXPENSE', null, 'OTHER', 'Para conta corrente', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-09');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Juros empréstimo', 30.00, '2024-01-11', 'INCOME', 'INTEREST', null, 'Empréstimo P2P', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-12');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'App de transporte', 22.50, '2024-01-13', 'EXPENSE', null, 'TRANSPORT', 'Viagem trabalho', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Consulta online', 90.00, '2024-01-17', 'EXPENSE', null, 'HEALTH', 'Telemedicina', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2024-01-18');

-- Julho 2025
-- Minha Carteira (25 transações)
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Salário mensal', 4800.00, '2025-07-05', 'INCOME', 'SALARY', null, 'Pagamento salário Julho', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2025-07-06');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Aluguel recebido', 1300.00, '2025-07-10', 'INCOME', 'RENTAL', null, 'Apartamento centro', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Supermercado', 380.25, '2025-07-12', 'EXPENSE', null, 'FOOD', 'Compras mensais', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2025-07-13');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Juros investimentos', 210.40, '2025-07-15', 'INCOME', 'INTEREST', null, 'Rendimento CDB', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2025-07-16');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Academia', 120.00, '2025-07-18', 'EXPENSE', null, 'HEALTH', 'Mensalidade', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Presente aniversário', 120.00, '2025-07-20', 'EXPENSE', null, 'OTHER', 'Presente para amigo', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2025-07-21');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Uber', 42.60, '2025-07-22', 'EXPENSE', null, 'TRANSPORT', 'Viagem aeroporto', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2025-07-23');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Netflix', 39.90, '2025-07-25', 'EXPENSE', null, 'ENTERTAINMENT', 'Assinatura mensal', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Venda de móveis', 550.00, '2025-07-28', 'INCOME', 'OTHER', null, 'Sofá usado', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2025-07-29');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Farmácia', 72.90, '2025-07-30', 'EXPENSE', null, 'HEALTH', 'Remédios', (SELECT id FROM wallets w WHERE w.name = 'Minha Carteira'), true, '2025-07-31');

-- Nubank (25 transações)
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Freelance desenvolvimento', 2200.00, '2025-07-05', 'INCOME', 'SALARY', null, 'Projeto app', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2025-07-06');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Dividendos ações', 180.75, '2025-07-10', 'INCOME', 'INVESTMENT', null, 'Ações B3', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Compras mercado', 95.00, '2025-07-12', 'EXPENSE', null, 'FOOD', 'Mercado rápido', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2025-07-13');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Rendimento poupança', 28.40, '2025-07-15', 'INCOME', 'INTEREST', null, 'Poupança digital', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2025-07-16');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Plano de saúde', 350.00, '2025-07-18', 'EXPENSE', null, 'HEALTH', 'Mensalidade', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Doação', 50.00, '2025-07-20', 'EXPENSE', null, 'OTHER', 'Doação instituição', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2025-07-21');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'App transporte', 35.00, '2025-07-22', 'EXPENSE', null, 'TRANSPORT', 'Viagem trabalho', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2025-07-23');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Assinatura música', 19.90, '2025-07-25', 'EXPENSE', null, 'ENTERTAINMENT', 'Streaming música', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), false, null);
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Venda de livros', 45.00, '2025-07-28', 'INCOME', 'OTHER', null, 'Livros usados', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2025-07-29');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation, wallet_id, is_realized, realized_date) VALUES (gen_random_uuid(), 'Consulta médica', 150.00, '2025-07-30', 'EXPENSE', null, 'HEALTH', 'Dermatologista', (SELECT id FROM wallets w WHERE w.name = 'Nubank'), true, '2025-07-31');
