INSERT INTO users (id, name, email, login, password, status, role) VALUES (gen_random_uuid(), 'Administrator', 'admin@email.com', 'admin', '$2a$10$WG9kEmAUsx9cTIBmdEynVOXthtZ/VmFTNubCutii5foQDoRAkq3eS','ACTIVE','ADMIN');

-- Janeiro 2024
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Salário mensal', 4500.00, '2024-01-05', 'INCOME', 'SALARY', null, 'Pagamento salário Janeiro');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Supermercado Extra', 156.78, '2024-01-07', 'EXPENSE', null, 'FOOD', 'Compras da semana');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Conta de energia elétrica', 89.45, '2024-01-10', 'EXPENSE', null, 'HOME', 'Vencimento 10/01');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Freelance desenvolvimento web', 800.00, '2024-01-12', 'INCOME', 'OTHER', null, 'Projeto site institucional');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Combustível posto Shell', 120.50, '2024-01-15', 'EXPENSE', null, 'TRANSPORT', 'Abastecimento completo');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Dividendos ações Itaú', 45.30, '2024-01-18', 'INCOME', 'INTEREST', null, 'Dividendos trimestrais');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Academia mensal', 85.00, '2024-01-20', 'EXPENSE', null, 'HEALTH', 'Mensalidade janeiro');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Venda produto usado', 250.00, '2024-01-22', 'INCOME', 'OTHER', null, 'Venda smartphone antigo');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Restaurante japonês', 95.80, '2024-01-25', 'EXPENSE', null, 'FOOD', 'Jantar com amigos');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Internet fibra ótica', 79.90, '2024-01-28', 'EXPENSE', null, 'HOME', 'Mensalidade internet');

-- Fevereiro 2024
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Consultoria técnica', 1200.00, '2024-02-03', 'INCOME', 'OTHER', null, 'Consultoria sistema ERP');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Farmácia remédios', 67.45, '2024-02-05', 'EXPENSE', null, 'HEALTH', 'Medicamentos prescritos');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Salário mensal', 4500.00, '2024-02-05', 'INCOME', 'SALARY', null, 'Pagamento salário Fevereiro');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Mercado atacado', 234.67, '2024-02-08', 'EXPENSE', null, 'FOOD', 'Compras mensais');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Streaming Netflix', 32.90, '2024-02-10', 'EXPENSE', null, 'ENTERTAINMENT', 'Assinatura mensal');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Uber viagens', 45.20, '2024-02-12', 'EXPENSE', null, 'TRANSPORT', 'Corridas semana');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Rendimento poupança', 15.78, '2024-02-15', 'INCOME', 'INTEREST', null, 'Rendimento mensal');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Material limpeza casa', 89.99, '2024-02-17', 'EXPENSE', null, 'HOME', 'Produtos limpeza');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Conta água e esgoto', 56.33, '2024-02-20', 'EXPENSE', null, 'HOME', 'Conta bimestral');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Cashback cartão', 23.45, '2024-02-22', 'INCOME', 'OTHER', null, 'Cashback compras');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Cinema ingresso', 28.00, '2024-02-25', 'EXPENSE', null, 'ENTERTAINMENT', 'Filme fim de semana');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Manutenção veículo', 450.00, '2024-02-28', 'EXPENSE', null, 'TRANSPORT', 'Revisão programada');

-- Março 2024
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Projeto mobile app', 2500.00, '2024-03-02', 'INCOME', 'OTHER', null, 'Desenvolvimento aplicativo');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Salário mensal', 4500.00, '2024-03-05', 'INCOME', 'SALARY', null, 'Pagamento salário Março');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Padaria café manhã', 12.50, '2024-03-07', 'EXPENSE', null, 'FOOD', 'Café e pão');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Plano saúde', 320.00, '2024-03-08', 'EXPENSE', null, 'HEALTH', 'Mensalidade plano');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Livros técnicos', 89.90, '2024-03-10', 'EXPENSE', null, 'EDUCATION', 'Livros programação');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Móveis sala', 850.00, '2024-03-12', 'EXPENSE', null, 'HOME', 'Mesa e cadeiras');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Venda consultoria', 600.00, '2024-03-15', 'INCOME', 'OTHER', null, 'Consultoria banco dados');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Telefone celular', 49.90, '2024-03-18', 'EXPENSE', null, 'HOME', 'Plano móvel');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Aplicação CDB', 1000.00, '2024-03-20', 'EXPENSE', null, 'OTHER', 'Investimento CDB');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Lanchonete delivery', 35.50, '2024-03-22', 'EXPENSE', null, 'FOOD', 'Pedido iFood');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Curso online Udemy', 79.90, '2024-03-25', 'EXPENSE', null, 'EDUCATION', 'Curso React Native');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Reembolso seguro', 180.00, '2024-03-28', 'INCOME', 'OTHER', null, 'Reembolso sinistro');

-- Abril 2024
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Salário mensal', 4500.00, '2024-04-05', 'INCOME', 'SALARY', null, 'Pagamento salário Abril');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Supermercado Carrefour', 198.43, '2024-04-07', 'EXPENSE', null, 'FOOD', 'Compras quinzenais');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Seguro veículo', 89.50, '2024-04-10', 'EXPENSE', null, 'TRANSPORT', 'Parcela mensal seguro');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Dentista consulta', 120.00, '2024-04-12', 'EXPENSE', null, 'HEALTH', 'Limpeza dental');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Aluguel recebido', 1200.00, '2024-04-15', 'INCOME', 'RENTAL', null, 'Aluguel apartamento');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Eletrodomésticos', 450.00, '2024-04-18', 'EXPENSE', null, 'HOME', 'Liquidificador e torradeira');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Transporte público', 65.00, '2024-04-20', 'EXPENSE', null, 'TRANSPORT', 'Recarga cartão ônibus');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Dividendos FII', 67.89, '2024-04-22', 'INCOME', 'INTEREST', null, 'Dividendos imobiliário');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Estacionamento shopping', 8.00, '2024-04-25', 'EXPENSE', null, 'TRANSPORT', 'Estacionamento 4h');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Festa aniversário', 200.00, '2024-04-28', 'EXPENSE', null, 'ENTERTAINMENT', 'Festa 30 anos');

-- Maio 2024
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Salário mensal', 4500.00, '2024-05-05', 'INCOME', 'SALARY', null, 'Pagamento salário Maio');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Energia elétrica', 145.67, '2024-05-08', 'EXPENSE', null, 'HOME', 'Conta bimestral');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Taxi aeroporto', 65.00, '2024-05-10', 'EXPENSE', null, 'TRANSPORT', 'Ida aeroporto');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Bonificação trabalho', 1000.00, '2024-05-12', 'INCOME', 'OTHER', null, 'Bonificação trimestral');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Pizza delivery', 48.90, '2024-05-15', 'EXPENSE', null, 'FOOD', 'Pizza família');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Spotify premium', 21.90, '2024-05-18', 'EXPENSE', null, 'ENTERTAINMENT', 'Assinatura música');
INSERT INTO transactions (id, description, amount, transaction_date, type, category_income, category_expense, observation) VALUES (gen_random_uuid(), 'Universidade mensalidade', 850.00, '2024-05-20', 'EXPENSE', null, 'EDUCATION', 'Pós-graduação maio');